<?php

use Drupal\image\Entity\ImageStyle;

/**
* Implementing hook theme, article list name of theme function
*/

function products_module_theme($existing, $type, $theme, $path){

    return array(
        'product_list' => array(
            'variables' => array('items' => array(),'title' => '', 'pager' => '')));
}

/** 
* Izvlacimo listu proizvoda bez parent reference. Umesto reference na Product, mentorka mi je predlozila da dodam novi content type "Company"
*/
function products_module_preprocess_node__company(&$variables) {
    $nids = \Drupal::entityQuery('node')->condition('type', 'product')
    ->condition('field_parent.entity', 'value', 'IS NULL')->execute();

    $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($nids);
    foreach($nodes as $item){
        $title= $item->title->getValue()[0]['value'];
        $variable['title'] = $title;
        $variables['products'][]=$variable;
}
}

function products_theme_registry_alter(&$theme_registry) {
  // You can add some conditions here in case you want
  // to override the form template only for some reasons.
  $theme_registry['form']['path'] = drupal_get_path('module', 'My_Module') . '/templates';
}

function products_theme_theme($existing, $type, $theme, $path) {
  return [
    'custom_form' => [
      'render element' => 'form',
    ]
  ];
}



