products_module.custom_form:
  title: 'Custom Form'
  description: 'Set the Default Count variable'
  route_name: products_module.custom_form
  menu_name: main
  parent: system

products_module.product_list:
  title: 'Product'
  description: 'List of all products'
  route_name: products_module.product_list
  menu_name: main
  weight: 100


