products_module.product_list:
  path: '/productlists'
  defaults:
    _title: 'Product list'
    _controller: '\Drupal\products_module\Controller\ProductController::product'
  requirements:
    _permission: 'configure_form'

products_module.custom_form:
  path: /admin/config/system/custom-form
  defaults:
    _form: 'Drupal\products_module\Form\CustomForm'
    _title: 'Custom Form'
  requirements:
    _permission: 'configure_form'