<?php

use Drupal\image\Entity\ImageStyle;
use \Drupal\Core\Cache\CacheBackendInterface;


/**
* Implementing hook theme, article list name of theme function
*/

function products_module_theme($existing, $type, $theme, $path){

    return array(
        'product_list' => array(
            'variables' => array('items' => array(),'title' => '', 'pager' => '')));
}

/** 
* Izvlacimo listu proizvoda bez parent reference. Umesto reference na Product, mentorka mi je predlozila da dodam novi content type "Company"
* Lista proizvoda bez parenta se vidi u menu linku "Products"
*/

function products_module_preprocess_node__company(&$variables) {
    
    $cache = \Drupal::cache();
    if($cache->get('stats.nodes')){
        $products=$cache->get('stats.nodes')->data;
    }
    else{
        $nids = \Drupal::entityQuery('node')->condition('type', 'product')
        ->condition('field_parent.entity', 'value', 'IS NULL')->execute();
        $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadMultiple($nids);
        $cache->set('stats.nodes', $nodes);
        $products=$cache->get('stats.nodes')->data;
    }
    
    foreach($products as $item){
        $title= $item->title->getValue()[0]['value'];
        $variable['title'] = $title;
        $variables['products'][]=$variable;
        $variables['#cache']['max-age'] = 3000;
    }
}



